# Generated by Django 3.0.4 on 2020-04-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=50)),
                ('invoice_number', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('other', models.CharField(max_length=300)),
            ],
        ),
    ]
